### ISSUE TITLE
A Lesson From This Attack.

### ISSUE THREAD

**Issue by Hawk2811** [Atheropids/SteamComrninuty-Phish-Spammer#1]
Had to Delete My Fucking Discord Account Because of this Shit So Get That Shit From Github

If It Wasn't You Try to Find It Because I'm already pissed off with this shit

and if this damn translator is bad, I'm from Brazil

**Comment by Atheropids** [comment]
**Calm down** and **read the description/readme on the project front page**, my friend. This is **NOT** a tool used to compromise Discord/Steam accounts. It's the opposite. We made the tool in order to **spam nonsense craps onto those phishing pages**, in effort of slowing down/impeding their malicious activities. If you hate those stupid phishing scumbags, you're attacking your friends.

Also, use Google Translate instead of random translation services/apps. Most of them are pure stinky pile of greedy ad-filled sh!t that flip the meanings of sentences.

Or should you be mad because we're making it difficult for you to steal accounts, go f*ck yourself. I guess it's not the case. I suppose cybercriminals wouldn't be that dumb to just show up here.

**Comment by Atheropids** [comment]
After some trivial inspections, I guess it would be nice to put some more off-topic details here.

Based on your location (Brazil) and the information I can retrieve from looking up for the username in the example screenshot, I'm pretty sure the account shown in the example belongs to you. **Read the following advice carefully if this is indeed the case.**

_First_, follow common sense. Do **NOT** download and run random stuffs from the internet without thorough inspections. Either if it's a cheat module for online games, cracked software, free gifts, free games, whatsoever. Get a decent anti-malware solution if you cannot follow this basic rule on your own. The built-in Microsoft Defender for Windows 10 should be fine for most end-users currently.

_Second_, **STAY AWAY** from random free virtual goodies promoted by others except from those official websites. Either from your online friends, or from users on social media you don't even know about. Those are very likely to be phishing attacks, aiming to steal your accounts with passwords or even financial credentials.

_Third_, **CHECK the DOMAIN NAME of a website you're currently trying to log into.** You can check it by just looking at your browser address bar on top. You should learn that the **domain name** in one of the most important part that tells if a website is definitely malicious. Here are some examples: `https://accounts.google.com/whatever/here/is/not/important` belongs to `google.com`, and thus can be trusted; while `https://nitro.discorrd.ru/free-nitro` belongs to `discorrd.ru`, not `discord.com`, thus you should be alerted and refrain from entering your login information on that page. **No matter how "official" the page appears, you should ALWAYS check the domain name first. No exception.** For links, you can check the destinations by hovering your cursor over them, and the URLs should show up in the bottom of your browser(s) in most of the cases, if you're on a PC.

I am pretty sure you're a techie teen, by looking into your repositories on your GitHub page. What I can help is telling you that you still have much more to learn about. Claiming to be a "hacker" does not make you any more superior than others. Moreover, you should be pursuing for the **hacker spirit** -- using the skills that others don't have to improve the well-being of our society, instead of looking for extra power for control or dominance.

I will also change the title of this ticket and re-open it, in order to have more people to learn about the incident and about how to protect themselves from falling victim. I expect you to not getting your new accounts stolen like this ever again.

Have a nice day. c:
